name: Deploy Backend to AWS
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust if you're using a different version
    - name: Install dependencies
      run: |
        cd backend
        npm ci
    - name: Run tests
      run: |
        cd backend
        npm test
    - name: Build application
      run: |
        cd backend
        npm run build  # Adjust if your build command is different
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: ${{ secrets.AWS_ROLE_SESSION_NAME }}
    - name: Deploy to Elastic Beanstalk
      run: |
        pip install awsebcli
        eb use EnvyBackend-env
        eb deploy
      env:
        ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_SECRET_ID: ${{ secrets.DB_SECRET_ID }}
        DB_USER: ${{ secrets.DB_USER }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        KEY: ${{ secrets.KEY }}
        REJECT_UNAUTHORIZED: ${{ secrets.REJECT_UNAUTHORIZED }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        USE_SSL: ${{ secrets.USE_SSL }}
